// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpznjmpfmyexvxpwwdnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwem5qbXBmbXlleHZ4cHd3ZG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTU3OTcsImV4cCI6MjA2NzQ5MTc5N30.qJGg3AwlNxOfi7wWRiVRGd-xG1Ob53WmOPrgqlnZmqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});